title: Adanna Obioha # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bioinformatician 
  <br><br>
  Data Scientist 
  <br><br>
  <a href="https://www.linkedin.com/in/adannaobioha/">View My LinkedIn Profile</a> 
  <a href="https://github.com/AdaObioha">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
